export const restaurantData = {
  restaurant: [
    {
      id: 1,
      name: "La PIZZA",
      location: "Ilupeju",
      food: [
        "Sharwama",
        "Chips",
        "Pizza",
        "Soda Drinks",
        "Youghurt",
        "Parfait",
      ],
    },
    {
      id: 2,
      name: "Chicken Republic",
      location: "Palmgroove",
      food: [
        "White Rice",
        "Jollof Rice",
        "Fried Rice",
        "Stew",
        "Soda Drinks",
        "Spaghetti",
      ],
    },
    {
      id: 3,
      name: "Bukka Hut",
      location: "alice.johnson@example.com",
      food: [
        "Amala",
        "Bitter Leaf Soup",
        "Oha Soup",
        "Egusi Soup",
        "Ewedu Soup",
        "Fish",
        "Soda Drinks",
        "Youghurt",
        "Fufu",
        "Semo",
        "Yam",
        "Boiled Egg",
        "White Rice",
        "Jollof Rice",
        "Fried Rice",
        "Stew",
        "Parfait",
        "Indomie",
        "Sauce",
        "Scotch Egg",
      ],
    },
    {
      id: 2,
      name: "NAS",
      location: "YCT",
      food: [
        "Bread",
        "Moi-moi",
        "Coffee",
        "Suya",
        "Stew",
        "Soda Drinks",
        "Spaghetti",
        "Boiled Egg",
        "White Rice",
        "Jollof Rice",
        "Fried Rice",
        "Stew",
      ],
    },
  ],
};

export const allFoods = {
  food: [
    { id: 1, item: "7up", img: "/7up.jpg", price: 500, category: "drinks" },
    {
      id: 2,
      item: "Amala",
      img: "/amala.jpg",
      price: 200,
      category: "swallow",
    },
    {
      id: 3,
      item: "Bitter Leaf Soup",
      img: "/bitterleaf.jpg",
      price: 1500,
      category: "soup",
    },
    { id: 4, item: "Bread", img: "/bread.jpg", price: 500, category: "main" },
    { id: 5, item: "Chips", img: "/chips.jpg", price: 800, category: "other" },
    {
      id: 6,
      item: "Coffee",
      img: "/coffee.jpg",
      price: 500,
      category: "add-ons",
    },
    { id: 7, item: "Coke", img: "/coke.jpg", price: 500, category: "drinks" },
    { id: 8, item: "Boiled Egg", img: "/cooked.jpg", price: 300, category: "add-ons" },
    { id: 9, item: "Egusi", img: "/egwusi.jpg", price: 1500, category: "soup" },
    { id: 10, item: "Ewedu", img: "/ewedu.jpg", price: 1500, category: "soup" },
    { id: 11, item: "Fanta", img: "/fanta.jpg", price: 500, category: "drinks" },
    { id: 12, item: "Fish", img: "/fish.jpg", price: 3500, category: "add-ons" },
    { id: 13, item: "Fried Rice", img: "/fried-rice.jpg", price: 4500, category: "main" },
    { id: 14, item: "Fufu", img: "/fufu.jpg", price: 250, category: "swallow" },
    { id: 15, item: "Indomie", img: "/indomie.jpg", price: 2500, category: "main" },
    { id: 16, item: "Jollof Rice", img: "/jellof.jpg", price: 3750, category: "main" },
    { id: 17, item: "Moi-moi", img: "/moi-moi.jpg", price: 500, category: "add-ons" },
    { id: 18, item: "Oha", img: "/oha.jpg", price: 1500, category: "soup" },
    { id: 19, item: "Okra", img: "/okra soup.jpg", price: 1500, category: "soup" },
    { id: 20, item: "Pepsi", img: "/pepsi.jpg", price: 500, category: "drinks" },
    { id: 21, item: "Parfait", img: "/perfait.jpg", price: 3750, category: "other" },
    { id: 22, item: "Pizza", img: "/pizza.jpg", price: 5000, category: "main" },
    { id: 23, item: "Sauce", img: "/sauce.jpg", price: 1500, category: "soup" },
    { id: 24, item: "Scotch Egg", img: "/scorge.jpg", price: 500, category: "other" },
    { id: 25, item: "Semo", img: "/semo.jpg", price: 350, category: "swallow" },
    { id: 26, item: "Shawarma", img: "/shawarma.jpg", price: 4500, category: "main" },
    { id: 27, item: "Spaghetti", img: "/spaghetti.jpg", price: 2500, category: "main" },
    { id: 28, item: "Sprite", img: "/sprite.jpg", price: 500, category: "drinks" },
    { id: 29, item: "Stew", img: "/stew.jpg", price: 1500, category: "soup" },
    { id: 30, item: "White Rice", img: "/white-rice.jpg", price: 1500, category: "main" },
    { id: 31, item: "Suya", img: "/suya.jpg", price: 4000, category: "other" },
    { id: 32, item: "Yam", img: "/yam.jpg", price: 3500, category: "main" },
    { id: 33, item: "Youghurt", img: "/yoghurt.jpg", price: 2500, category: "other" },
  ],
};
